version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Web Tier Build Completed"
artifacts:
  files:
    - '**/*'
  base-directory: build
