# buildspec-destroy.yml
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Terraform
      - curl -O https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform_1.7.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Setting up backend
      - terraform init
  build:
    commands:
      - echo Destroying all infrastructure...
      - terraform destroy -auto-approve
